echo java MapClient WHYdeMacBook-Air.local 30123 "put:foo:bar"
java MapClient WHYdeMacBook-Air.local 30123 "put:foo:bar"
echo java MapClient WHYdeMacBook-Air.local 30123 "put:who:hah"
java MapClient WHYdeMacBook-Air.local 30123 "put:who:hah"
echo java MapClient WHYdeMacBook-Air.local 30123 "put:goodbye:world"
java MapClient WHYdeMacBook-Air.local 30123 "put:goodbye:world"
echo java MapClient WHYdeMacBook-Air.local 30123 "get:foo"
java MapClient WHYdeMacBook-Air.local 30123 "get:foo"
echo java MapClient WHYdeMacBook-Air.local 30123 "get:who"
java MapClient WHYdeMacBook-Air.local 30123 "get:who"
echo java MapClient WHYdeMacBook-Air.local 30123 "remove:who"
java MapClient WHYdeMacBook-Air.local 30123 "remove:who"
echo java MapClient WHYdeMacBook-Air.local 30123 "get:who"
java MapClient WHYdeMacBook-Air.local 30123 "get:who"
echo java MapClient WHYdeMacBook-Air.local 30123 "get:goodbye"
java MapClient WHYdeMacBook-Air.local 30123 "get:goodbye"
echo java MapClient WHYdeMacBook-Air.local 30123 "got:goodbye"
java MapClient WHYdeMacBook-Air.local 30123 "got:goodbye"
echo java MapClient WHYdeMacBook-Air.local 30123 "pat:goodbye:world"
java MapClient WHYdeMacBook-Air.local 30123 "pat:goodbye:world"
echo java MapClient WHYdeMacBook-Air.local 30123 "get:bar"
java MapClient WHYdeMacBook-Air.local 30123 "get:bar"
echo java MapClient WHYdeMacBook-Air.local 30123 "put:foo:\"toast is tasty\""
java MapClient WHYdeMacBook-Air.local 30123 "put:foo:\"toast is tasty\""
echo java MapClient WHYdeMacBook-Air.local 30123 "get:foo"
java MapClient WHYdeMacBook-Air.local 30123 "get:foo"
